name: Rococo Slot Request
description: "Please use this issue for requests related to your slot on Rococo"
labels: [Rococo]
body:
  - type: markdown
    attributes:
      value: |
        ## BEFORE you continue complete the [Parachain Tutorials](https://docs.substrate.io/tutorials/build-a-parachain/)!
  - type: checkboxes
    id: tutorial-complete
    attributes:
      label: You completed the Parachain Tutorials for your parachain and tested locally?
      description: "We _insist_ that you have tested locally with `rococo-local` at the identical version of the presently running Rococo is using _before_ you can apply for a slot!"
      options:
        - label: "Yes, we have successfully tested our chain on `rococo-local`."
          required: true
  - type: input
    id: team-name
    attributes:
      label: Team Name
      description: "The company, group, or individual requesting the slot."
      placeholder: "Example: Parity Technologies"
    validations:
      required: true
  - type: input
    id: para-name
    attributes:
      label: Parachain Name
      description: "The name of your Parachain"
      placeholder: "Example: Rocmint"
    validations:
      required: true
  - type: input
    id: para-id
    attributes:
      label: ParaID
      description: "The paraID that you ***compiled in your chainspec***. If **short-term**, this should already be registered on Rococo with the associated with the genesis state and Wasm for the paraID. If a **long-term** slot, this should ***match the chain you have a slot on for Kusama and/or Polkadot***!"
      placeholder: "Example: 3000"
    validations:
      required: true
  - type: input
    id: manager-account
    attributes:
      label: Parachain Manager Account
      description: "A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account when filling this field."
      placeholder: "Example:5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
    validations:
      required: true
  - type: dropdown
    id: para-id-term
    attributes:
      label: Is this for a short or long term slot?
      description: "If short-term, please **double-check the paraID you registered as a parathread is in place**. If long-term, please ensure your paraID from Kusama/Polkadot is free/unused on Rococo."
      options:
        - "Short-term: we registered a parathread with the paraID above."
        - "Long-term: we have a matching paraID in use on Polkadot or Kusama."
    validations:
      required: true
  - type: textarea
    id: genesis
    attributes:
      label: Upload your Genesis Head (genesis state) - Do not submit a compressed file.
      placeholder: Drag & drop or upload the genesis file, or provide a link to this file to download
    validations:
      required: true
  - type: textarea
    id: wasm
    attributes:
      label: Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.
      placeholder: Drag & drop or upload the Wasm runtime file associated with your genesis
    validations:
      required: true
  - type: textarea
    id: chain-spec
    attributes:
      label: (Optional) Upload your Chain Specification
      description: "Example: https://github.com/paritytech/polkadot/blob/master/node/service/res/rococo.json"
      placeholder: Drag & drop or upload the chain spec file associated with your genesis
    validations:
      required: false
  - type: textarea
    id: what-else
    attributes:
      label: Anything else we should know?
      description: Please let the Rococo team know anything else about this request, and details about your
      value: So... We want to start a XCM channel with X parachain with Y paraID...
    validations:
      required: false
  - type: textarea
    id: apps-ui-pr
    attributes:
      label: Register your Rococo parachain details for `polkadot-js/apps`
      description: |
        So that users can identify what chain you are using, please submit a PR to <https://github.com/polkadot-js/apps/> to include your details on the UI

        **Example PR: https://github.com/polkadot-js/apps/pull/7180/files**

        You _may_ leave this as the default text below, but need to add the PR when it's in started or merged.
      value: |
        <!-- You _may_ leave this as the default text below, but need to add the PR when it's in started or merged -->

        <!-- Example PR: https://github.com/polkadot-js/apps/pull/7180/files -->
        - [ ] Polkadot-js Apps UI PR completed
          - Available here: {FIX ME!!!!}
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### If you need support for your team related to this slot, please use this issue for further requests. Like opening VMP channels with Rococo or using `sudo` on Rococo for your team.
